title: Loriqeet
description: Dynamic custom images for social media sharing.
baseurl: ""
url: "https://loriqeet.com"
username: loriqeet
formspreeurl: https://formspree.io/f/mvodqlwp

defaults:
  - scope:
      path: "*"
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

sass:
  style: :compressed
