title: Loriqeet
description: Dynamic custom images for social media sharing
baseurl: ""
url: "https://loriqeet.com"
username: loriqeet

defaults:
  - scope:
      path: "*"
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
