title: Loriqeet
description:
baseurl: "/loriqeet"
url: "https://loriqeet.github.io"
username: loriqeet

defaults:
  - scope:
      path: "*"
    values:
      layout: default

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
